Ch  setup and deploy base application to heroku 181151229
Emmanuel-Dominic/writers-space-invictus-backend pull request #11
Opened 2022-02-24 14:13 UTC by semitalatimothy

### What does this PR do?
 - This PR configures the app to be deployed on Heroku
 
### Description of Task to be completed?
- create heroku account
- create heroku pipe lines
- configure app for heroku
- test app on heroku

### How should this be manually tested?

 -  https://writers-space-invictus-backend.herokuapp.com/
 
### Any background context you want to provide?
 -  No
 
### What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/story/show/181151229
 
### Screenshots (if appropriate)

### Questions:
 - None
 
[start #181151229]

2022-02-25 14:00 UTC, Emmanuel-Dominic requested changes, later dismissed
**Edit you pull request title and also the project on Heroku is failing with the error below, fix it please as you also ensure the project isn't in DEBUG mode**

![heroku-error](https://user-images.githubusercontent.com/50827537/155727589-10aa0657-c419-4738-997f-f622068a000e.PNG)

2022-02-25 14:00 UTC, Emmanuel-Dominic commented on authors/settings.py
> +ALLOWED_HOSTS = ['writers-space-invictus-backend.herokuapp.com']
- **why list the hostname like this here?**
- **what is the use of this ALLOWED_HOSTS declaration here?**

2022-02-25 14:00 UTC, Emmanuel-Dominic commented on requirements.txt
> +whitenoise==6.0.0
- **Why all these packages, I think we only need the main packages installed from the terminal?**

2022-02-25 15:30 UTC, semitalatimothy commented on requirements.txt
> +whitenoise==6.0.0
The packages have been updated.

2022-03-11 14:01 UTC, Daniel-Kigozi approved these changes

2022-03-11 14:42 UTC, Daniel-Kigozi approved these changes

2022-03-14 08:45 UTC, semitalatimothy commented on authors/settings.py
> +ALLOWED_HOSTS = ['writers-space-invictus-backend.herokuapp.com']
This has been resolved

2022-03-14 13:47 UTC, bogerepau approved these changes
Looks good welldone Tim

2022-03-15 13:50 UTC, Victoria129 approved these changes

2022-03-15 21:56 UTC, Emmanuel-Dominic approved these changes

2022-03-15 21:57 UTC, merged