#181151230 Configure Authors Haven to use PostgreSQL as DB Engine
Emmanuel-Dominic/writers-space-invictus-backend pull request #8
Opened 2022-02-13 13:22 UTC by Victoria129

####  What does this PR do?
- Configures Authors Haven to use PostgreSQL as DB Engine

####  Description of Task to be completed?
- Create PostgreSQL database
- Configure Authors Haven to use PostgreSQL as DB Engine

####  How should this be manually tested?
- A database with a database name is created; In this case, the database name used is "**Invictus**".
- By running **"psql -U postgres"**, provide a password if required, run "**postgres=# \c invictus;**", (invictus is the name of the database). In order to see the tables that have been created, run **"invictus=# \dt;"**.
 
####  Any background context you want to provide?
- No

####  What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/181151230

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/69035525/154684254-38450944-cab8-48a4-981e-21f691c7201f.png)

![image](https://user-images.githubusercontent.com/69035525/154673878-76dc170b-4278-4339-92c3-aafce8e5e07c.png)

####  Questions:
- None

[Start #181151230]

2022-02-13 13:41 UTC, Emmanuel-Dominic requested changes
Try to rebase with **develop**, to expect charges done in only two files ie settings.py and requirements.txt

2022-02-13 13:41 UTC, Emmanuel-Dominic commented on authors/settings.py
> +
Nice work, though take time to learn about how to set environment variables with python.

2022-02-13 13:41 UTC, Emmanuel-Dominic commented on requirements.txt
> +tzdata==2021.5
I can't see the Postgres dependency/adapter listed here.

2022-02-18 12:39 UTC, Emmanuel-Dominic approved these changes
LGTM

2022-02-18 12:41 UTC, Daniel-Kigozi commented
Looks okay

2022-02-18 12:43 UTC, Daniel-Kigozi approved these changes

2022-02-18 12:43 UTC, semitalatimothy approved these changes

2022-02-18 12:43 UTC, merged

2022-02-18 12:43 UTC, bogerepau commented
It is working fine